### ISSUE TITLE
Max sprite count exceeds max value

### ISSUE THREAD

**Issue by rgrams** [britzl/defold-bunnymark#1]
Trying to build and run from the editor on Windows, it crashes with this error:

>ERROR:GAMESYS: Max sprite count (30000) exceeds max value (16384).

**Comment by rgrams** [comment]
1ccbe5823a6fd4d672c1ca5743cf82026a283dc0 👍 

I'm curious though, is this a new limit? I could have sworn I had tested things with more than 16384 sprites before.

**Comment by britzl** [comment]
Yes, this is a change introduced in 1.2.119 as a result of the sprite optimisations done. We have changed to indexed vertex buffers (instead of triangle lists) which has a limit of 65536 bytes which translates to 16384 sprites.
